// Mocks generated by Mockito 5.4.0 from annotations
// in super_daily_habits/test/features/today/domain/bloc/today_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i17;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:super_daily_habits/common/domain/common_repository.dart'
    as _i10;
import 'package:super_daily_habits/features/today/domain/day_repository.dart'
    as _i5;
import 'package:super_daily_habits/features/today/domain/entities/activity/habit_activity.dart'
    as _i9;
import 'package:super_daily_habits/features/today/domain/entities/activity/habit_activity_creation.dart'
    as _i7;
import 'package:super_daily_habits/features/today/domain/entities/custom_date.dart'
    as _i4;
import 'package:super_daily_habits/features/today/domain/entities/custom_time.dart'
    as _i15;
import 'package:super_daily_habits/features/today/domain/entities/day/day.dart'
    as _i2;
import 'package:super_daily_habits/features/today/domain/entities/day/day_base.dart'
    as _i8;
import 'package:super_daily_habits/features/today/domain/helpers/activity_completition_validator.dart'
    as _i13;
import 'package:super_daily_habits/features/today/domain/helpers/activity_text_controllers_generator.dart'
    as _i11;
import 'package:super_daily_habits/features/today/domain/helpers/current_date_getter.dart'
    as _i12;
import 'package:super_daily_habits/features/today/domain/helpers/day_calificator.dart'
    as _i16;
import 'package:super_daily_habits/features/today/domain/helpers/time_range_calificator.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDay_0 extends _i1.SmartFake implements _i2.Day {
  _FakeDay_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomDate_2 extends _i1.SmartFake implements _i4.CustomDate {
  _FakeCustomDate_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextSelection_3 extends _i1.SmartFake implements _i3.TextSelection {
  _FakeTextSelection_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingValue_4 extends _i1.SmartFake
    implements _i3.TextEditingValue {
  _FakeTextEditingValue_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextSpan_5 extends _i1.SmartFake implements _i3.TextSpan {
  _FakeTextSpan_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [DayRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDayRepository extends _i1.Mock implements _i5.DayRepository {
  MockDayRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Day> getDayByDate(_i4.CustomDate? date) => (super.noSuchMethod(
        Invocation.method(
          #getDayByDate,
          [date],
        ),
        returnValue: _i6.Future<_i2.Day>.value(_FakeDay_0(
          this,
          Invocation.method(
            #getDayByDate,
            [date],
          ),
        )),
      ) as _i6.Future<_i2.Day>);
  @override
  _i6.Future<_i2.Day> setActivityToDay(
    _i7.HabitActivityCreation? activity,
    _i2.Day? day,
    int? newRestantWork,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActivityToDay,
          [
            activity,
            day,
            newRestantWork,
          ],
        ),
        returnValue: _i6.Future<_i2.Day>.value(_FakeDay_0(
          this,
          Invocation.method(
            #setActivityToDay,
            [
              activity,
              day,
              newRestantWork,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Day>);
  @override
  _i6.Future<_i2.Day> createDay(_i8.DayBase? day) => (super.noSuchMethod(
        Invocation.method(
          #createDay,
          [day],
        ),
        returnValue: _i6.Future<_i2.Day>.value(_FakeDay_0(
          this,
          Invocation.method(
            #createDay,
            [day],
          ),
        )),
      ) as _i6.Future<_i2.Day>);
  @override
  _i6.Future<_i2.Day> updateActivityRestantWork(
    int? restantWork,
    _i2.Day? day,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActivityRestantWork,
          [
            restantWork,
            day,
          ],
        ),
        returnValue: _i6.Future<_i2.Day>.value(_FakeDay_0(
          this,
          Invocation.method(
            #updateActivityRestantWork,
            [
              restantWork,
              day,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Day>);
  @override
  _i6.Future<_i2.Day> deleteHabitFromDay(
    _i9.HabitActivity? habit,
    _i2.Day? day,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHabitFromDay,
          [
            habit,
            day,
          ],
        ),
        returnValue: _i6.Future<_i2.Day>.value(_FakeDay_0(
          this,
          Invocation.method(
            #deleteHabitFromDay,
            [
              habit,
              day,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Day>);
  @override
  _i6.Future<List<_i9.HabitActivity>> getAllRepeatableActivities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRepeatableActivities,
          [],
        ),
        returnValue:
            _i6.Future<List<_i9.HabitActivity>>.value(<_i9.HabitActivity>[]),
      ) as _i6.Future<List<_i9.HabitActivity>>);
}

/// A class which mocks [CommonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommonRepository extends _i1.Mock implements _i10.CommonRepository {
  MockCommonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> setCommonWork(int? work) => (super.noSuchMethod(
        Invocation.method(
          #setCommonWork,
          [work],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<int> getCommonWork() => (super.noSuchMethod(
        Invocation.method(
          #getCommonWork,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
}

/// A class which mocks [ActivityTextControllersGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityTextControllersGenerator extends _i1.Mock
    implements _i11.ActivityTextControllersGenerator {
  MockActivityTextControllersGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TextEditingController get nameController => (super.noSuchMethod(
        Invocation.getter(#nameController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#nameController),
        ),
      ) as _i3.TextEditingController);
  @override
  _i3.TextEditingController get minutesDurationController =>
      (super.noSuchMethod(
        Invocation.getter(#minutesDurationController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#minutesDurationController),
        ),
      ) as _i3.TextEditingController);
  @override
  _i3.TextEditingController get workController => (super.noSuchMethod(
        Invocation.getter(#workController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#workController),
        ),
      ) as _i3.TextEditingController);
  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);
  @override
  void generate() => super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateNameController(String? newValue) => super.noSuchMethod(
        Invocation.method(
          #updateNameController,
          [newValue],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateMinutesDurationController(String? newValue) => super.noSuchMethod(
        Invocation.method(
          #updateMinutesDurationController,
          [newValue],
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic updateWorkController(String? newValue) =>
      super.noSuchMethod(Invocation.method(
        #updateWorkController,
        [newValue],
      ));
}

/// A class which mocks [CurrentDateGetter].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentDateGetter extends _i1.Mock implements _i12.CurrentDateGetter {
  MockCurrentDateGetter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CustomDate getTodayDate() => (super.noSuchMethod(
        Invocation.method(
          #getTodayDate,
          [],
        ),
        returnValue: _FakeCustomDate_2(
          this,
          Invocation.method(
            #getTodayDate,
            [],
          ),
        ),
      ) as _i4.CustomDate);
}

/// A class which mocks [ActivityCompletitionValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityCompletitionValidator extends _i1.Mock
    implements _i13.ActivityCompletitionValidator {
  MockActivityCompletitionValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isCompleted(_i7.HabitActivityCreation? activity) => (super.noSuchMethod(
        Invocation.method(
          #isCompleted,
          [activity],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [TimeRangeCalificator].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeRangeCalificator extends _i1.Mock
    implements _i14.TimeRangeCalificator {
  MockTimeRangeCalificator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool timeIsBetweenTimeRange(
    _i15.CustomTime? time,
    _i15.CustomTime? rangeInit,
    int? minutesDuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeIsBetweenTimeRange,
          [
            time,
            rangeInit,
            minutesDuration,
          ],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool timeRangesCollide(
    _i15.CustomTime? initialTime1,
    int? duration1,
    _i15.CustomTime? initialTime2,
    int? duration2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeRangesCollide,
          [
            initialTime1,
            duration1,
            initialTime2,
            duration2,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [DayCalificator].
///
/// See the documentation for Mockito's code generation for more information.
class MockDayCalificator extends _i1.Mock implements _i16.DayCalificator {
  MockDayCalificator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool canBeModified(
    _i2.Day? day,
    _i4.CustomDate? currentDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canBeModified,
          [
            day,
            currentDate,
          ],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool hasEnoughRestantWork(
    _i2.Day? day,
    int? workToAdd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasEnoughRestantWork,
          [
            day,
            workToAdd,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [TextEditingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextEditingController extends _i1.Mock
    implements _i3.TextEditingController {
  MockTextEditingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: '',
      ) as String);
  @override
  set text(String? newText) => super.noSuchMethod(
        Invocation.setter(
          #text,
          newText,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set value(_i3.TextEditingValue? newValue) => super.noSuchMethod(
        Invocation.setter(
          #value,
          newValue,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.TextSelection get selection => (super.noSuchMethod(
        Invocation.getter(#selection),
        returnValue: _FakeTextSelection_3(
          this,
          Invocation.getter(#selection),
        ),
      ) as _i3.TextSelection);
  @override
  set selection(_i3.TextSelection? newSelection) => super.noSuchMethod(
        Invocation.setter(
          #selection,
          newSelection,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.TextEditingValue get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _FakeTextEditingValue_4(
          this,
          Invocation.getter(#value),
        ),
      ) as _i3.TextEditingValue);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i3.TextSpan buildTextSpan({
    required _i3.BuildContext? context,
    _i3.TextStyle? style,
    required bool? withComposing,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildTextSpan,
          [],
          {
            #context: context,
            #style: style,
            #withComposing: withComposing,
          },
        ),
        returnValue: _FakeTextSpan_5(
          this,
          Invocation.method(
            #buildTextSpan,
            [],
            {
              #context: context,
              #style: style,
              #withComposing: withComposing,
            },
          ),
        ),
      ) as _i3.TextSpan);
  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clearComposing() => super.noSuchMethod(
        Invocation.method(
          #clearComposing,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool isSelectionWithinTextBounds(_i3.TextSelection? selection) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSelectionWithinTextBounds,
          [selection],
        ),
        returnValue: false,
      ) as bool);
  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
